hapjs-platform/hapjs

README.md
=> 修改 README 中的部分关键字

core/runtime/android/runtime/src/main/java/org/hapjs/component/utils/FullscreenHelper.java
=> 全屏播放退出时概率空指针异常 (#36)

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/picker/DatePicker.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/picker/MultiPicker.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/picker/Picker.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/picker/TextPicker.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/picker/TimePicker.java
Change-Id: I9265a0bbc2d27f9f779a84f17274265f9262d2ca
=> 重构picker #12

core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Image.java
Change-Id: Idccbbcef4df060379d58ece18f205a45e1c9917e
=> SysOpProvider增加handleImageForceDark #15

.github/workflows/main.yml
根据之前的反馈，重新做了调整，主要的更新：
- 使用更合适的账号提交
- squash 多个 commit 之后提交
- 更新使用的容器
- 删除结尾提示性的说明
经过fork项目测试通过
=> Support Github Action

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/lrucache/LruCache.java
Change-Id: I228ec66c4a0d43f33ed8f6f712b5ff35469c75eb
=> 开启pageCache时, 活动销毁可能会出现ConcurrentModificationException #7

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java
Change-Id: If444e72cf9cc5ac68719c1a8c3370de5e39013c6
=> video组件支持 border-[top|bottom]-[left|right]-radius #17

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/canvas/canvas2d/CanvasContextRendering2D.java
Change-Id: Idd45bd8b76fca7df3bdf18625be4cbeb7bfc1f5a
Signed-off-by: liquan <liquan.rjyb@vivo.com>
=> [#56]修复canvas的globalCompositeOperation属性在文字和图形混合时失效

core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java
fix #46
Change-Id: Ie569df98ddee6eb49639cc54c03992162659120b
=> Android 10 夜间模式支持自定义Image显示

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DefaultStatusBarSizeProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DisplayUtil.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/StatusBarSizeProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/Runtime.java
Change-Id: Id391cf79870220104b9a27f2bba2af33c8fa7f9b
=> 通过provider返回statusbar高度, 便于定制 #13

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/sectionlist/SectionList.java
Change-Id: Ic441ec3d184f83072953c8218db61bde3501002a
=> [#63] 修复SectionList的滑动到顶端和底端的事件不生效的问题

Jenkinsfile
Change-Id: Iede8080ddaf266033ad9306827b5e65fa55b99ff
=> [#66]修复联盟1090分支编译时的tag问题

core/runtime/android/runtime/src/main/java/org/hapjs/component/RecyclerDataItem.java
Change-Id: I7ac84ca6fb13182a08baee198875e25e44418e05
=> [#71] 修复list中的元素的appear事件未触发问题

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/drawer/Drawer.java
Change-Id: Ib69c7d332be97473cfa42d7bf4a9b87c79dedba5
(cherry picked from commit 443deaece70b02ad5deec8365d1a33f7200981c6)
=> [#75]修复抽屉组件滑动状态错误的问题

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/WebViewUtils.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
Change-Id: I85205ff7277fdbf28955f999c5038b69d74f2c25
Signed-off-by: gen.tian <gen.tian@vivo.com>
=> [#79] web组件文件多选失败

core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/utils/FullscreenHelper.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
Change-Id: I154c7bf43fdb8f57eefce867dec1c0387ed49c29
=> 【#89】web组件退出全屏后白屏问题 

core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java
Change-Id: Ie2d4552545045a530d9934790fd6f8904e5c681d
Signed-off-by: gen.tian <gen.tian@vivo.com>
=> [#81]优化修改：将RootView 生命周期方法中的for循环遍历改为迭代器遍历 

core/runtime/android/runtime/src/main/java/org/hapjs/component/view/webview/BaseWebViewClient.java
Change-Id: I3536d6aa76e115d3d7fcdaa131a4fc1b03c1d2a6
=> [#83]优化修改：拦截webview渲染崩溃

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/text/Marquee.java
Change-Id: Icbd0bdb40dc842a7d90ca7b46ee85f76ec5f38ea
Signed-off-by: gen.tian <gen.tian@vivo.com>
=> [ #87]Marquee组件导致的崩溃问题

core/framework/sys-components/vue/src/sys/web/index.vue, core/framework/sys-components/xvm/src/sys/web/index.ux, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/HybridRequest.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/net/UserAgentHelper.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/WebPage.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/WebViewModule.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Web.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
Change-Id: Icab6191eb851a4a760d077265793383468467304
=> [#95]Web组件支持自定义UA

core/runtime/android/features/src/main/java/org/hapjs/features/Clipboard.java
Change-Id: Idea4d3684b77bcbe54aff32eb9f4fdd70e959b86
=> [#146]在剪贴板Clipboard接口增加调用埋点上报空方法

core/runtime/android/runtime/src/main/java/org/hapjs/component/feature/AnimationFeature.java
Change-Id: Ia24c91a44f9dc79e1c294a7c019cdbd4096b4d41
=> [#105] AnimationFeature # enable 方法缺少判空引起空指针异常

core/runtime/android/runtime/src/main/java/org/hapjs/component/animation/Animation.java
Change-Id: I8eb8a29ec21f1ecd3004baec39b2fb7a3342176b
=> [#104] animation 数组中元素的 animatorSet 成员变量已经被销毁导致空指针

core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentBackgroundComposer.java
Change-Id: I00f828d4e261c0e9174b986d73cd784788f391f1
=> [#113] background 因复用导致不生效，补充修改2

core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentBackgroundComposer.java
Change-Id: Ia88a66f79a1fee5195ad9fabcf5f337282e5c460
=> [#106] 元素背景颜色默认值黑色与 H5 透明色不一致

core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/flexbox/PercentFlexboxLayout.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/list/ListItem.java
Change-Id: I281e40d81c6e4be475140bc2e99f9e2ff61ca67a
=> [#110] list-item 新增点击事件拦截控制属性 disallowintercept

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Swiper.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/swiper/LoopPagerAdapter.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/swiper/SwiperView.java
Change-Id: I7d8ee7087a9072e50aad20cc153fb72b1dee75d3
=> [#116] swiper 删除页面后未更新后一页的位置并重设指示器

core/runtime/android/runtime/src/main/java/org/hapjs/component/transition/OpacityTransition.java
Change-Id: I3dc4610f37ce167cd3400e8e604ac84149b9c967
=> [#109] OpacityTransition # createAnimator 遗漏判空操作引起空指针异常

core/runtime/android/runtime/src/main/java/org/hapjs/component/utils/FullscreenHelper.java
Change-Id: Icb5b27af58c9068c9c4394525f13edbd00b9b8a3
=> [#103] Video 横屏或竖屏全屏退出时不能通过 setFullscreenVisibility 方法恢复 UI

core/runtime/android/features/src/main/java/org/hapjs/features/Sensor.java
Change-Id: I5d6d31ae47f0ee7d6cb6e194478e6c48948c4591
=> [#150]sensor.subscribeProximity增加判断当前设备是否支持距离传感器提示

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/SlideView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/slideview/SecondaryConfirmInfo.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/slideview/SlideButtonInfo.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/slideview/SlideViewLayout.java
=> [#100]slideview组件open/close方法缺省参数处理

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/sectionlist/SectionGroup.java
Change-Id: Iccfa38acf5a19c2cdae74b93df141bab3d566fc1
=> [#73] 修复section-group组件的onchange事件回调失败

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/MediaController.java
Change-Id: I4f07c5a06407ab0e65b68bf9c03cc152258ae921
=> [#111] MediaController 中 dispatchKeyEvent 方法遗漏播放器判空引起空指针异常

core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java
This reverts commit e999298c27ca870c5cf1c3f70893048dfda8cb35.
Change-Id: Ib80db41568d6060fec7674a757427fcc8f1aa860
=> [#147]Revert " 支持广告组件"

core/framework/package-lock.json, core/framework/package.json
Change-Id: I44ea8789402d660c82fbd8d7a8148f2f11418a9c
=> [#52] 修改framework及toolkit版本号

core/framework/src/dsls/xvm/vm/directive.js
Change-Id: Ic572dad0f4d767641b076c649d3c221f9669a96e
=> [#54] fix issue

core/runtime/android/runtime/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/runtime/src/main/res/values/strings.xml
Change-Id: I96ed76c37fecb2df9b87e43e941d4f202af8fdf7
=> [#92]优化跳转app弹窗字符串

core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java
Change-Id: I09894a005b5c9b84cc726b9a522470ac57a3f989
[#58 ](url)
=> [#58]:花样短视频在Android5的机型上，灭屏后可以继续播放

core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentBackgroundComposer.java
Change-Id: I57efe629e7709fe9803f56c8f5dbd97c5cf75cc9
Signed-off-by: louzixuan <zixuan.lou@vivo.com>
=> [#130] select组件设置背景颜色时，右侧下拉箭头会消失

core/runtime/android/runtime/src/main/java/org/hapjs/component/view/drawable/SizeBackgroundDrawable.java
Change-Id: I67daad7c699907da008154a75118953976725143
Signed-off-by: louzixuan <zixuan.lou@vivo.com>
=> [#121]background-size设置为' '时应用崩溃问题

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/CameraView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/VideoRecordMode.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/CameraSurfaceRender.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/MediaMuxerController.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/TextureMovieEncoder.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/common/VideoHandlerThread.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/gles/FullFrameRect.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/gles/GlUtil.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/record/gles/Texture2dProgram.java
Signed-off-by: cmc <mingcan.chen@vivo.com>
=> [#160]camera 压测问题

core/runtime/android/runtime/src/main/java/org/hapjs/pm/DefaultNativePackageProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/pm/NativePackageProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
Change-Id: If6c6b5c6a4f895352bb670351766b6892f970a57
=> [#172]网页跳转支付宝url黑名单

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java
Change-Id: Id095c62992232498e6d73bf90a6fc684ce08571a
=> [#163]video问题修复-视频控制器显示问题

core/runtime/android/runtime/src/main/java/org/hapjs/model/videodata/VideoCacheManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java
Change-Id: If672289bc3888ccdf6b5d3634bce5dfc3b1cdaca
=> [#162]video问题修复-autoplay问题

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/CameraView.java
Change-Id: I2e125a89300c4eab66daadba8bd31e940e4b1a88
=> [#159]camera横竖屏切换相机角度调整

core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/PageModule.java
Change-Id: I49a97158d902d9fca2cad2af56594d006e251173
=> [#164]menubar坐标适配设计尺寸

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/PackageUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/UriUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/gesture/GestureDelegate.java, core/runtime/android/runtime/src/main/java/org/hapjs/pm/DefaultNativePackageProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/pm/NativePackageProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/DefaultRouterManageProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/RouterManageProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/Runtime.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
修改原因:无
解决方法:无
Change-Id: I65ab88b352eff3f36fea12b109cbffb2d454cfb5
=> [#173]快应用调起快应用跳端管控

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/PackageUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/RouterUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java
修改原因:无
解决方法:无
Change-Id: I84e90de1d7b07f447375166fbf5ed7a26958ceef
=> [#176]快应用调起快应用跳端管控埋点

core/runtime/android/runtime/src/main/java/org/hapjs/render/skeleton/PathParser.java, core/runtime/android/widgets/src/main/java/androidx/recyclerview/widget/HapStaggeredGridLayoutManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/refresh/CircleImageView.java
=> CircleImageView.java等3个文件缺少版权声明

core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentBackgroundComposer.java
This reverts commit 6025077b808d1e2076fbe9feecb9d90818974a50.
=> Revert "[#113] background 因复用导致不生效，补充修改2"

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java
Change-Id: I0ac6a3e36833396b28bc5603abf3f68c4a31eb3b
Signed-off-by: xiaopengfei <pengfei.xiao@vivo.com>
=> [#107] FlexVideoView # setVideoURI 方法参数为空时出现空指针异常

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/canvas/canvas2d/CSSFont.java
Change-Id: I22b444e05c45e61b82138e1e4bca38873817f7c9
=> [#209]canvas设置快应用中text支持的font-family不生效

core/runtime/android/features/src/main/java/org/hapjs/features/geolocation/GeolocationProviderImpl.java
=> [#215]拉起百度导航来源未上报问题修复

core/runtime/android/runtime/src/main/java/org/hapjs/component/animation/CSSAnimatorSet.java
=> [#217] 后台无效动画回调占用CPU耗电

core/runtime/android/features/src/main/AndroidManifest.xml, core/runtime/android/features/src/main/java/org/hapjs/features/screenshot/Screenshot.java, core/runtime/android/features/src/main/java/org/hapjs/features/screenshot/ScreenshotObserver.java
=> [#242]增加快应用截屏监听接口及bug修复

core/runtime/android/runtime/src/main/java/org/hapjs/common/location/LocationClient.java
=> [#229]位置信息接口增加gps模块判断

core/runtime/android/features/src/main/java/org/hapjs/features/Alarm.java, core/runtime/android/features/src/main/java/org/hapjs/features/Media.java, core/runtime/android/features/src/main/java/org/hapjs/features/video/Video.java
=> [#237]Media、Video、Alarm的getFileName方法增加对uri判空

core/runtime/android/features/src/main/java/org/hapjs/features/Device.java
=> [#234]获取设备信息接口增加获取屏幕当前刷新率字段

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/storage/file/ResourceFactory.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java
=> [#214]增加快应用的文件访问校验避免media接口漏洞问题

core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/WebViewModule.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Web.java
=> [#230] webview新增设置cookie接口

debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/debug/AppDebugManager.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/fragment/AppFragment.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/utils/HttpUtils.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/utils/PreferenceUtils.java, debug/shell/android/app-impl/src/main/res/layout/content_main.xml, debug/shell/android/app-impl/src/main/res/values-zh-rCN/strings.xml, debug/shell/android/app-impl/src/main/res/values/strings.xml
=> [#249] 调试器增加性能面板入口

core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/widgets/build.gradle, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/text/Text.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/text/TextSpan.java
=> [#310]增加text与a标签的letter-spacing属性

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/BitmapUtils.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/A.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Image.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/InnerSpannable.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/NestedInnerSpannable.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Span.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/text/Text.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/text/TextLayoutView.java
=> [#293]新增支持图文混排

core/runtime/android/runtime/src/main/java/org/hapjs/model/ConfigInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/GrayModeConfig.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/GrayModeInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/DecorLayout.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/ConfigurationModule.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/GrayModeManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/HapEngine.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Camera.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Popup.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Select.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/map/Map.java, platform/platform/android/platform/src/main/java/org/hapjs/LauncherActivity.java, platform/platform/android/platform/src/main/java/org/hapjs/PlatformRuntime.java
=> [#292]新增灰色模式

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/MenubarUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Display.java
=> [#285]menubar通用方法参数兼容

core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Display.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Page.java
=> [#284]menubar分享当前页面参数配置优化

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/image/FlexImageView.java
=> [hapjs-platform#283]fresco升级后图片圆角锯齿问题

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/MenubarUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/gesture/GestureDelegate.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ShareButton.java
=> [#289]新增分享按钮组件

debug/shell/android/app-impl/src/main/AndroidManifest.xml, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/AppLaunchTestActivity.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/SignatureActivity.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/fragment/DebugFragment.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/utils/PreferenceUtils.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/BlurLinearLayout.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/BlurRelativeLayout.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/BlurShadowButton.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/LastChildVisibleLinearLayout.java, debug/shell/android/app-impl/src/main/res/layout/activity_draggable.xml, debug/shell/android/app-impl/src/main/res/layout/activity_main.xml, debug/shell/android/app-impl/src/main/res/layout/content_app.xml, debug/shell/android/app-impl/src/main/res/layout/content_card.xml, debug/shell/android/app-impl/src/main/res/values/styles.xml
=> [#315]【1100版本调试器】调试器首页及其子项优化bug修复

core/framework/src/dsls/xvm/index.js, core/framework/src/dsls/xvm/page/interface.js, core/framework/src/dsls/xvm/page/misc.js, core/framework/src/infras/dock/bootstrap.js, core/framework/src/infras/dock/interface.js, core/framework/src/infras/dock/page/index.js, core/framework/src/infras/dock/page/misc.js, core/framework/src/infras/runtime/listener.js
=> [#259] framework新增 $nextTick 方法

core/framework/src/dsls/xvm/vm/index.js, core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/MenubarView.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/gesture/GestureDelegate.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Display.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/PageModule.java, core/runtime/android/runtime/src/main/res/layout/titlebar_view.xml, core/runtime/android/runtime/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/runtime/src/main/res/values/strings.xml, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/input/EventButton.java
=> [hapjs-platform#287] 添桌组件

core/runtime/android/features/src/main/java/org/hapjs/features/Notification.java, core/runtime/android/features/src/main/java/org/hapjs/features/ShortMessage.java, core/runtime/android/features/src/main/java/org/hapjs/features/audio/service/MediaNotificationManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/resident/ResidentService.java
=> [#305] Notification接口等地方创建的PendingIntent没有指定响应的应用名, 有安全风险

core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java
=> [#303] 使用clear_task flag打开快应用页面时崩溃

core/runtime/android/features/src/main/java/org/hapjs/features/Clipboard.java
=> [#302] sample快应用里，在安卓7上的clipboard无法获得剪切文本

core/framework/src/infras/platform/module/misc.js
=> [#299]JS框架新增SYNC_CALLBACK类型

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/storage/file/UriTmpResource.java
=> [#296] file.get接口预期支持tmp文件,实际结果fail,errcode=300

core/runtime/android/features/src/main/java/org/hapjs/features/Alarm.java, core/runtime/android/features/src/main/java/org/hapjs/features/Contact.java, core/runtime/android/features/src/main/java/org/hapjs/features/Device.java, core/runtime/android/features/src/main/java/org/hapjs/features/Media.java, core/runtime/android/features/src/main/java/org/hapjs/features/Sensor.java, core/runtime/android/features/src/main/java/org/hapjs/features/preview/PreviewImageDialog.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/ExtensionManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/Response.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/permission/HapPermissionManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/permission/PermissionCallback.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/permission/RuntimePermissionProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/map/MapProxy.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/CameraView.java, platform/platform/android/platform/src/main/java/org/hapjs/permission/RuntimePermissionProviderImpl.java
=> [#277]优化权限申请方式

core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Page.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java
=> [#264] manifest配置文件中支持页面动画定制

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/FileUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/DefaultFontFamilyProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/FontFamilyProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/Runtime.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/text/FontParser.java
=> [#266] font-face src 支持系统字体

core/runtime/android/features/src/main/java/org/hapjs/features/net/CallbackWrapper.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTask.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTaskImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/storage/file/InternalUriUtils.java
=> [#271]download请求支持进度事件通知及abort能力

core/runtime/android/runtime/src/main/java/org/hapjs/model/ConfigInfo.java
=> [#304]fix:designWidth=device-width时屏幕点击坐标数据错误问题

core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/widgets/build.gradle, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/lottie/FlexLottie.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/lottie/Lottie.java
=> [#348]增加lottie组件

core/runtime/android/features/src/main/java/org/hapjs/features/AbstractRequest.java, core/runtime/android/features/src/main/java/org/hapjs/features/Geolocation.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentBackgroundComposer.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/vdom/DocComponent.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/image/FlexImageViewAttach.java
=> [#332] AbstractRequest导致activity泄露等几个内存泄露问题

core/runtime/android/card-support/src/main/java/org/hapjs/card/support/CardView.java, core/runtime/android/card-support/src/main/java/org/hapjs/card/support/impl/CardServiceWorker.java, core/runtime/android/runtime/src/main/java/org/hapjs/chunk/JsChunksManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/FrescoUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/AppResourcesLoader.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/PageManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/WebPage.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/JsThread.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/Runtime.java, platform/platform/android/platform/src/main/java/org/hapjs/DispatcherActivity.java, platform/platform/android/platform/src/main/java/org/hapjs/LauncherActivity.java
=> [#360] 优化快应用启动速度

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java, core/runtime/android/widgets/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/widgets/src/main/res/values/strings.xml
=> [#355] 优化webrtc弹窗的文案, 方便进行多语言翻译

core/runtime/android/features/src/main/java/org/hapjs/features/Network.java
=> [#357] getSimOperators方法删除READ_PHONE_STATE权限

core/runtime/android/runtime/build.gradle
=> [#359] 增加1100 V8边界情况校验.

core/runtime/android/runtime/src/main/java/org/hapjs/component/view/BaseTitleDialog.java
=> [#363] 偶发SimpleDraweeView初始化时崩溃

core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTask.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTaskImpl.java
=> [#372] fix：DownloadTask存在文件名、类型跟参数不一致等问题

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/UriUtils.java, platform/platform/android/platform/src/main/AndroidManifest.xml, platform/platform/android/platform/src/main/java/org/hapjs/launch/DeepLinkClient.java
=> [#333] 支持qr.quickapp.cn域名跳转快应用

mockup/platform/android/app-impl/src/main/java/org/hapjs/mockup/app/AppManager.java, mockup/platform/android/app-impl/src/main/java/org/hapjs/mockup/impl/DistributionProviderImpl.java, platform/platform/android/platform/src/main/java/org/hapjs/PlatformRuntime.java, platform/platform/android/platform/src/main/java/org/hapjs/cache/SrpkPackageInstallerBase.java, platform/platform/android/platform/src/main/java/org/hapjs/distribution/DistributionManager.java, platform/platform/android/platform/src/main/java/org/hapjs/distribution/DistributionService.java, platform/platform/android/platform/src/main/java/org/hapjs/distribution/InstalledSubpackageManager.java
=> [#335] 优化分包安装状态的查询效率

core/runtime/android/card-support/src/main/java/org/hapjs/card/support/CardView.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/SimpleActivityLifecycleCallbacks.java
=> [#330] 增加SimpleActivityLifecycleCallbacks简化ActivityLifecycleCallbacks使用

platform/platform/android/platform/src/main/java/org/hapjs/utils/ShortcutUtils.java
=> [#323]使用单个包名判断原生应用是否安装

core/runtime/android/runtime/src/main/java/org/hapjs/render/action/RenderActionDocument.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/css/CSSStyleSheet.java
=> [#325]fix:RenderActionNode未释放造成的内存泄露

core/runtime/android/runtime/src/main/java/org/hapjs/render/action/RenderActionManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/action/RenderActionParser.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/css/Node.java
=> [#328] 偶现快应用打开时崩溃

platform/platform/android/platform/src/main/java/org/hapjs/utils/ActivityUtils.java
=> [#329] Activity finish后, ActivityUtils.getCallingPackage(Activity activity)返回null

debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/fragment/AppFragment.java
=> [#381]删除AppFragment无用的打印日志

core/runtime/android/runtime/src/main/java/org/hapjs/logging/LogProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ShortcutButton.java
=> [#290]新增添桌按钮组件

debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/fragment/DebugFragment.java
=> [#362]android 5上新版调试器点击调试须知无反应，打开问题反馈崩溃问题修复

debug/shell/android/app-impl/build.gradle
=> [#365]安卓5：调试器-设置-帮助：使用说明、常见问题、开发文档、开发者社区打开就黑屏闪退

debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/SignatureActivity.java, debug/shell/android/app-impl/src/main/res/layout/display_sign_layout.xml
=> [#367]v1100调试器无法获取快应用签名短信hash

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/DefaultRouterManageProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/RouterManageProvider.java
=> [#306]inRouterForbiddenList 方法增加 ResolveInfo 参数

core/runtime/android/features/src/main/AndroidManifest.xml, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/IsoDepInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/MifareClassicInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/MifareUltralightInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NFC.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NFCAdapterInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NFCConstants.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NFCUtils.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NdefInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NfcAInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NfcBInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NfcFInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/NfcVInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/base/BaseInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/base/BaseTagTechInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/nfc/base/BaseTechInstance.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/HybridManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/ReflectUtils.java
=> [#225]NFC支持

core/runtime/android/features/src/main/java/org/hapjs/features/ad/impl/BannerAdInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/ad/impl/InterstitialAdInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/ad/impl/NativeAdInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/ad/impl/RewardedVideoAdInstance.java, core/runtime/android/features/src/main/java/org/hapjs/features/ad/instance/BaseAdInstance.java
=> [#275]广告错误提示优化

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/FeatureBridge.java
=> [#212]FeatureMap多线程问题修复

core/runtime/android/features/src/main/java/org/hapjs/features/Request.java
=> [#221] request接口DownloadManager remove方法执行时间超时导致anr

.github/workflows/main.yml
=> [#387] ci编译脚本需要指定flavor

debug/shell/android/app-impl/build.gradle, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/AppLaunchTestActivity.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/MainActivity.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/fragment/DebugFragment.java, debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/fragment/DebugFragmentManager.java, debug/shell/android/app-impl/src/main/res/values-zh-rCN/strings.xml, debug/shell/android/app-impl/src/main/res/values/strings.xml
=> [#386]修复调试器无法点击下载和启动应用测试问题

Jenkinsfile, core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/widgets/build.gradle, core/runtime/android/widgets/src/main/java/androidx/recyclerview/widget/FlexRecyclerView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/list/List.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/image/FlexImageViewAttach.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/list/FlexGridLayoutManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/list/FlexLayoutManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/list/FlexStaggeredGridLayoutManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/list/RecyclerViewAdapter.java, core/runtime/android/widgets/src/tv/java/androidx/leanback/widget/GridLayoutManagerAdapterImpl.java, core/runtime/android/widgets/src/tv/java/androidx/leanback/widget/GridViewAdapterImpl.java, core/runtime/android/widgets/src/tv/java/org/hapjs/widgets/tv/list/List.java, mockup/platform/android/app/src/main/AndroidManifest.xml, mockup/platform/android/app/src/tv/AndroidManifest.xml
=> [#383] tv上list组件新增onseleted事件和focusbehavior属性

core/framework/src/dsls/xvm/vm/compiler.js, core/framework/src/dsls/xvm/vm/directive.js, core/framework/src/dsls/xvm/vm/index.js, core/framework/src/infras/dock/app/index.js, core/framework/src/infras/dock/interface.js, core/framework/src/infras/dock/page/misc.js, core/framework/src/infras/runtime/dom/misc.js, core/framework/src/infras/runtime/listener.js
=> [#322] framework 新增自定义指令功能

debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/SettingsActivity.java
=> [#413]【1100调试器】拆分debugger问题与反馈到hapjs-ext

core/runtime/android/annotation-processor/src/main/java/org/hapjs/build/generator/ExtensionMetaData.java, core/runtime/android/annotation/src/main/java/org/hapjs/bridge/Extension.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/RequestHelper.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTask.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/RequestTask.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/RequestTaskImpl.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/UploadCallbackImpl.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/UploadTask.java, core/runtime/android/features/src/main/java/org/hapjs/features/net/task/UploadTaskImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/ExtensionManager.java
=> [#414] 对齐微信小程序能力，request/upload支持进度事件通知及abort事件

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#253]修复Android 12机器上H5页面输入框获取焦点后键盘抖动

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Web.java
=> [#252]完善web组件与H5双向通信时的callback处理逻辑

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java
=> [#411] 全屏播放视频可截屏

core/framework/src/dsls/xvm/vm/compiler.js
fix #273
Add logic for richetext when textType is book.
=> [#273] fix: 前端支持图书翻页能力

core/framework/src/infras/dock/page/misc.js
=> [#399]setTimeout中使用async/await关键字，回调方法不执行

core/framework/src/dsls/xvm/index.js, core/framework/src/dsls/xvm/page/interface.js, core/framework/src/dsls/xvm/page/misc.js, core/framework/src/dsls/xvm/vm/compiler.js, core/framework/src/dsls/xvm/vm/index.js, core/framework/src/infras/dock/app/index.js, core/framework/src/infras/dock/page/misc.js
=> [#409]增加部分场景边界情况校验

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/ExtensionManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/FeatureInnerBridge.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/MenubarUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/JsThread.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#282]feature接口调用抽离并放到jsthread线程

core/framework/src/dsls/xvm/vm/compiler.js, core/framework/test/suite/dsls/xvm/page/05.model/directive/for/base/index.test.js, core/framework/test/suite/dsls/xvm/page/05.model/directive/for/base/index.ux
=> [#401]for指令支持固定值

core/framework/src/dsls/xvm/util.js, core/framework/src/dsls/xvm/vm/compiler.js, core/framework/src/dsls/xvm/vm/directive.js, core/framework/src/infras/dock/interface.js, core/framework/test/suite/dsls/xvm/page/05.model/component/externalclasses/index.test.js, core/framework/test/suite/dsls/xvm/page/05.model/component/externalclasses/index.ux, core/framework/test/suite/dsls/xvm/page/05.model/component/externalclasses/part1.ux, core/framework/test/suite/dsls/xvm/page/05.model/component/externalclasses/part2.ux, core/framework/test/suite/dsls/xvm/page/05.model/component/externalclasses/part3.ux
=> [#403]增加父组件覆盖子组件样式能力

core/framework/src/dsls/xvm/vm/directive.js, core/framework/test/suite/dsls/xvm/page/05.model/component/$attrs/index.test.js, core/framework/test/suite/dsls/xvm/page/05.model/component/array/index.test.js
=> [#405]vm.$attrs 兼容先前版本

core/runtime/android/runtime/src/main/java/org/hapjs/runtime/DefaultRouterManageProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/RouterManageProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#426]增加网页拉起支付黑名单

core/framework/package.json, core/framework/src/dsls/xvm/app/bundle.js, core/framework/src/dsls/xvm/app/custom.js, core/framework/src/dsls/xvm/app/interface.js, core/framework/src/dsls/xvm/index.js, core/framework/src/dsls/xvm/page/bundle.js, core/framework/src/dsls/xvm/page/executor.js, core/framework/src/dsls/xvm/plugin-i18n/format.js, core/framework/src/dsls/xvm/plugin-i18n/index.js, core/framework/src/dsls/xvm/plugin-i18n/util.js, core/framework/src/dsls/xvm/vm/compiler.js, core/framework/src/dsls/xvm/vm/directive.js, core/framework/src/dsls/xvm/vm/index.js, core/framework/src/dsls/xvm/vm/watcher.js, core/framework/src/infras/bundles/parser/htmlparser.js, core/framework/src/infras/bundles/parser/transfer.js, core/framework/src/infras/dock/app/index.js, core/framework/src/infras/dock/bootstrap.js, core/framework/src/infras/dock/interface.js, core/framework/src/infras/dock/page/misc.js, core/framework/src/infras/platform/interface.js, core/framework/src/infras/platform/promise.js, core/framework/src/infras/platform/session.js, core/framework/src/infras/runtime/dom/nodes/element.js, core/framework/test/suite/dsls/xvm/page/05.model/state/undeclared/index.test.js
=> [#407]JS Framework日志优化

NOTICE
=> [#429] NOTICE增加spotbugs和spotbugs-gradle-plugin license声明

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/ExtensionManager.java
=> [#432] downloadtask.downloadFile()创建实例失败

NOTICE, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/ExtensionManager.java
=> downloadtask.downloadFile()创建实例失败，增加spotbugs声明

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java
=> [#436] 全屏播放视频可截屏对前端暴露

core/framework/src/dsls/xvm/vm/watcher.js
=> [#438] 使用了自定义指令的动态组件，快速切换组件时会报错

core/runtime/android/runtime/src/main/java/org/hapjs/render/AppResourcesLoader.java
=> [#444] IDE上修改代码，热更新后真机上显示还是修改前的内容

debug/engine/android/inspector/build.gradle, mockup/platform/android/build.gradle
=> [#446] mockup支持x86架构

core/runtime/android/runtime/src/main/java/org/hapjs/analyzer/AnalyzerDetectionManager.java, core/runtime/android/runtime/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/runtime/src/main/res/values/strings.xml
=> [#455] 调试面板布局深度等提示文案没使用plurals不便于翻译

core/runtime/android/features/src/main/java/org/hapjs/features/Clipboard.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/permission/HapCustomPermissions.java, core/runtime/android/runtime/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/runtime/src/main/res/values/strings.xml
=> [#465]剪贴板接口Clipboard新增写入剪贴板和访问剪贴板自定义权限

core/runtime/android/features/src/main/java/org/hapjs/features/screenshot/ScreenshotObserver.java
=> [#468]高android版本上出现截屏监听接口监听截屏失效

core/runtime/android/features/src/main/java/org/hapjs/features/Prompt.java, core/runtime/android/features/src/main/res/layout/prompt_loading_layout.xml
=> [#474]Prompt接口增加无障碍适配空方法，实现客制化需求

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/permission/SystemPermissionManager.java
优化系统权限请求方式，相同权限不同接口同时请求只显示一次权限请求
fix https://github.com/hapjs-platform/hapjs/issues/458
=> [#458] 系统权限请求时候，相同权限不同接口同时请求会显示多次权限请求

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/CallbackWrapper.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/ExtensionManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java
=> [#477]增加Feature调用结果统计

core/framework/src/dsls/xvm/vm/index.js, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/HybridRequest.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/RouterUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/TabBarInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Page.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/PageManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/TabBar.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/PageModule.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/RouterModule.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/adapter/TabBarItemAdapter.java, core/runtime/android/runtime/src/main/res/layout/tabbar_item_view.xml, core/runtime/android/runtime/src/main/res/layout/tabbar_view.xml, core/runtime/android/runtime/src/main/res/values/colors.xml
=> [#219]新增tabbar组件

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DisplayUtil.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/gesture/GestureDelegate.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ReaderDiv.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/readerdiv/ReaderLayoutView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/readerdiv/ReaderPageData.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/readerdiv/ReaderPageLayout.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/readerdiv/ReaderPageView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/readerdiv/ReaderText.java, core/runtime/android/widgets/src/main/res/layout/reader_page_container.xml, core/runtime/android/widgets/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/widgets/src/main/res/values/colors.xml, core/runtime/android/widgets/src/main/res/values/ids_reader.xml, core/runtime/android/widgets/src/main/res/values/strings.xml
=> [#500]新增小说组件

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/MediaUtils.java
=> [#478]快应用分享功能可泄露用户隐私照片或视频

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/PackageUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#482]跳端管控埋点增加跳转结果说明

core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/JsThread.java
=> [#472]空指针问题修复

core/runtime/android/runtime/src/main/java/org/hapjs/cache/Cache.java
=> [#480]Cache类getIconUri方法出现空指针

core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/animation/AnimationParser.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/animation/CSSAnimatorSet.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/animation/Transform.java
=> [#486]动画 transform 支持 translateZ

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Web.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#487]web组件支持屏蔽内部链接跳转

core/runtime/android/features/src/main/java/org/hapjs/features/Prompt.java
=> [#498]Prompt接口多线程重复移除loadingView报IllegalStateException

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/ShortcutManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/Source.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, platform/platform/android/platform/src/main/java/org/hapjs/system/PlatformSysOpProviderImpl.java
=> [#495]桌面图标安装结果接口增加type（图标类型）, serverIconUrl（图标icon下载地址）参数，实现客制化需求

core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/JsThread.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/ConfigurationManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/HapConfiguration.java
=> [#489]onConfigurationChanged事件新增对orientation/screenSize变化的支持

core/runtime/android/runtime/src/main/java/org/hapjs/render/Display.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java
=> [#490]快应用页面支持厂商指定屏幕方向

core/runtime/android/runtime/src/main/java/org/hapjs/model/videodata/VideoCacheManager.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java
=> [ #503]video问题修复-autoplay仅页面渲染时第一次初始化有效

core/runtime/android/runtime/src/main/java/org/hapjs/render/Display.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/vdom/DocComponent.java
=> [#505]全屏状态栏问题

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/camera/CameraView.java
=> [#506]camera录像功能-增加权限检测

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/DefaultFitWidescreenProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/bridge/FitWidescreenProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/AppInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/HapEngine.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/Runtime.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java
=> [#488]manifest.display 增加宽屏适配模式参数

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/BitmapUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/FoldingUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentBackgroundComposer.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Image.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Swiper.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/image/FlexImageView.java
=> [#509]新增折叠屏UI自适应功能

core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/adcustom/AdCustom.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/adcustom/AdCustomContainer.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/adcustom/AdCustomDataProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/adcustom/AdCustomDataProviderImpl.java
=> [#512]支持模板广告

core/runtime/android/card-support/src/main/java/org/hapjs/card/support/CardView.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/FoldingUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/RouterUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/ViewUtils.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/MultiWindowManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Page.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/PageManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/JsThread.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/vdom/DocAnimator.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/vdom/DocComponent.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/vdom/VDocument.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/HapConfiguration.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java
fix https://github.com/hapjs-platform/hapjs/issues/511
=> [#511]新增平行视界模式

core/runtime/android/runtime/src/main/java/org/hapjs/common/compat/BuildPlatform.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, mockup/platform/android/app/src/car/java/org/hapjs/mockup/MockupRuntime.java, mockup/platform/android/build.gradle
=> [#521]增加car flavor

core/runtime/android/features/src/main/java/org/hapjs/features/ad/Ad.java, core/runtime/android/features/src/main/java/org/hapjs/features/ad/NativeAd.java, core/runtime/android/features/src/main/java/org/hapjs/features/ad/instance/BaseNativeAdInstance.java, core/runtime/android/runtime/src/main/java/org/hapjs/ad/AdProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/ad/AdProxy.java, core/runtime/android/runtime/src/main/java/org/hapjs/ad/NativeAdEntity.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ad/Ad.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ad/AdClickArea.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ad/AdContainer.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ad/AdProxyImpl.java
=> [#523]支持原生信息流广告

core/runtime/android/runtime/src/main/java/org/hapjs/common/net/OkHttpClientBuilderFactory.java
=> #519参考业界安全规范要求，https, websocket等网络请求必须要求限定在tls1.2及以上 

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/ExoPlayer.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/IMediaPlayer.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Player.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/PlayerProxy.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java
=> [#528] 增加video组件播放倍速设置功能

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/FlexVideoView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/video/MediaController.java
=> [#530] 增加video组件暂停回调时的状态码

core/runtime/android/features/src/main/java/org/hapjs/features/Record.java
=> [#533]system.record接口支持分段返回PCM音频数据

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/ColorUtil.java, core/runtime/android/runtime/src/main/java/org/hapjs/logging/RuntimeLogManager.java, core/runtime/android/runtime/src/main/res/values-zh-rCN/strings.xml, core/runtime/android/runtime/src/main/res/values/strings.xml, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ShortcutButton.java
=> [#535] 添桌组件限制优化

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/FeatureInnerBridge.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/MenubarUtils.java
=> [#541]menubar接口调用校验问题修改

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ReaderDiv.java
=> [#555]readerdiv适配非750设计尺寸字体大小限定

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#557] 对webview选择文件的返回值做校验

core/runtime/android/runtime/src/main/java/org/hapjs/common/net/OkHttpClientBuilderFactory.java
=> [#561]修复ssl设置android版本兼容性判断错误，导致部分android版本出现ssl协议建议导致网络访问故障

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#564]web组件H5页面输入框显示异常问题

core/runtime/android/features/src/main/AndroidManifest.xml
=> [#565]没有声明权限导致监听计步传感器数据接口失效问题修复

core/runtime/android/runtime/src/main/java/org/hapjs/debug/DebugService.java, platform/platform/android/platform/src/main/java/org/hapjs/debug/SrpkDebugService.java
=> [#558] 安卓13，开启性能面板后，点击开始调试无反应，关闭后正常

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#557]解决对webview选择文件的返回值做校验引入的bug

core/runtime/android/runtime/src/main/java/org/hapjs/render/Display.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/PageModule.java
=> [#578]优化menubar坐标返回基于页面参数返回

core/runtime/android/runtime/src/main/java/org/hapjs/common/net/OkHttpClientBuilderFactory.java
=> [#575]修复调试器-性能面板-网络面板无内容

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/NestedWebView.java
=> [#557]完善解决对webview选择文件的返回值做校验

core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/readerdiv/ReaderText.java
=> [#590]小说组件适配不同系统字体

core/framework/src/dsls/xvm/app/bundle.js, core/framework/src/dsls/xvm/index.js, core/framework/src/dsls/xvm/page/misc.js, core/framework/src/dsls/xvm/plugin-i18n/index.js, core/framework/src/dsls/xvm/vm/compiler.js, core/framework/src/dsls/xvm/vm/directive.js, core/framework/src/dsls/xvm/vm/index.js, core/framework/src/dsls/xvm/vm/linker.js, core/framework/src/dsls/xvm/vm/watcher.js, core/framework/src/infras/bundles/animation/index.js, core/framework/src/infras/dock/app/index.js, core/framework/src/infras/dock/app/misc.js, core/framework/src/infras/dock/interface.js, core/framework/src/infras/dock/page/misc.js, core/framework/src/infras/dock/timer.js, core/framework/src/infras/platform/module/misc.js, core/framework/src/infras/runtime/dom/nodes/target.js, core/framework/src/shared/error.js, core/framework/src/shared/util.js, core/framework/test/suite/bridge/util.js, core/framework/test/suite/dsls/xvm/app/app.ux, core/framework/test/suite/dsls/xvm/app/plugin-demo.js, core/framework/test/suite/dsls/xvm/page/00.actions/sequence/index.test.js, core/framework/test/suite/dsls/xvm/page/01.base/error/index.test.js, core/framework/test/suite/dsls/xvm/page/01.base/error/index.ux, core/framework/test/suite/dsls/xvm/page/01.base/error/part1.ux, core/framework/test/suite/dsls/xvm/page/01.base/error/part2.ux, core/framework/test/suite/dsls/xvm/page/01.base/error/part3.ux, core/framework/test/suite/dsls/xvm/page/01.base/status/index.test.js
=> [#547] js-framework 新增错误捕获机制

core/framework/src/dsls/xvm/vm/index.js, core/framework/src/dsls/xvm/vm/watcher.js, core/framework/src/infras/dock/page/misc.js, core/framework/src/infras/platform/module/misc.js, core/framework/src/shared/error.js, core/framework/test/suite/dsls/xvm/page/01.base/error/index.test.js, core/framework/test/suite/dsls/xvm/page/01.base/error/index.ux, core/framework/test/suite/dsls/xvm/page/01.base/error/part3.ux
=> [#592] 完善 js-framework 错误捕获机制

core/runtime/android/features/src/main/java/org/hapjs/features/storage/data/LocalStorageFeature.java
=> [#595]数据存储storage增加同步调用

core/runtime/android/features/src/main/java/org/hapjs/features/CipherFeature.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DigestUtils.java
=> [#613][watch适配]新增三种加密方式

core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/DefaultComponentProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Image.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/image/FlexImageView.java, platform/platform/android/platform/src/main/java/org/hapjs/PlatformRuntime.java
=> [#615] image组件支持图片显示质量配置

core/framework/src/infras/dock/page/misc.js, core/framework/src/infras/dock/timer.js
=> [#612] 修复定时器回调未删除带来的轻微内存泄漏问题

GOVERNANCE.md
=> [#603]增加提名Collaborator文件GOVERNANCE.md

CODE_OF_CONDUCT.md
=> [#601]增加行为守则文件CODE_OF_CONDUCT.md

core/runtime/android/runtime/src/main/java/org/hapjs/render/RootView.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/LocaleResourcesParser.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/resource/CacheProviderContracts.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/resource/LocalResourceManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/resource/RemoteResourceManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/resource/ResourceManager.java, platform/platform/android/platform/src/main/java/org/hapjs/cache/CacheProvider.java
=> [#622] 【1300联盟版本】快应用卡片支持多语言(rfc:#0001)

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DisplayUtil.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/Component.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/ComponentProvider.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/DefaultComponentProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/constants/Attributes.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/RoundCornerImageView.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/view/drawable/SizeBackgroundDrawable.java, core/runtime/android/runtime/src/main/java/org/hapjs/model/DisplayInfo.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/Page.java, core/runtime/android/runtime/src/main/java/org/hapjs/render/jsruntime/module/ConfigurationModule.java, core/runtime/android/runtime/src/main/java/org/hapjs/runtime/ConfigurationManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/DefaultSysOpProviderImpl.java, core/runtime/android/runtime/src/main/java/org/hapjs/system/SysOpProvider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Image.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Select.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/ShortcutButton.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/SlideView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Slider.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/Span.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/input/Button.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/input/Edit.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/input/EventButton.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/input/TextArea.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/text/Marquee.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/text/Text.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/image/FlexImageView.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/slideview/SecondaryConfirmInfo.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/slideview/SlideButtonInfo.java, core/runtime/android/widgets/src/main/java/org/hapjs/widgets/view/slideview/SlideViewLayout.java
rfc：https://github.com/hapjs-platform/rfcs/pull/11
=> [hapjs-platform#635]【1300开源版本】快应用适配系统显示大小调整

core/runtime/android/runtime/src/main/java/org/hapjs/bridge/HybridManager.java, core/runtime/android/runtime/src/main/java/org/hapjs/component/animation/CSSAnimatorSet.java
=> [hapjs-platform#620]动画JE问题修改

core/runtime/android/features/src/main/java/org/hapjs/features/CipherFeature.java, core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DigestUtils.java
=> [#638]system.cipher CRC32 异常

core/plugins/android/features/asr/src/main/java/org/hapjs/features/service/asr/Asr.java
=> [#643] fix: 卸载语音引擎，调用asr.start接口回调了success 

core/plugins/android/features/asr/src/main/java/org/hapjs/features/service/asr/Asr.java
=> [#643] fix: 卸载语音引擎，调用asr.start接口回调了success

core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/NavigationUtils.java
=> [#656]部分手机跳转到手机系统的5G网络设置管理界面失败

core/runtime/android/runtime/build.gradle
=> fix: node resource download failed error
